# NumPy Assignment Solutions

## 1. Array Manipulation Challenge

Create a 3D NumPy array of shape (5, 4, 3) filled with random integers between 0 and 100. Perform the following operations:
- Extract all elements greater than 50
- Calculate the mean along the second axis
- Replace all elements less than 20 with the value -1
- Reshape the array to (10, 6) without changing its data

In [1]:
import numpy as np

# Create 3D array
arr = np.random.randint(0, 101, size=(5, 4, 3))
print("Original array:")
print(arr)

# Extract elements > 50
greater_than_50 = arr[arr > 50]
print("\nElements greater than 50:")
print(greater_than_50)

# Calculate mean along second axis
mean_second_axis = np.mean(arr, axis=1)
print("\nMean along second axis:")
print(mean_second_axis)

# Replace elements < 20 with -1
arr[arr < 20] = -1
print("\nArray after replacing elements < 20 with -1:")
print(arr)

# Reshape array to (10, 6)
reshaped_arr = arr.reshape(10, 6)
print("\nReshaped array:")
print(reshaped_arr)

Original array:
[[[ 29  57  90]
  [ 11  58  76]
  [  4  95  51]
  [ 77  97  65]]

 [[ 74  98  74]
  [100  45  69]
  [  3  88  69]
  [ 39  65  16]]

 [[  6  24  65]
  [ 53  14  35]
  [ 44  35   5]
  [ 76  76   6]]

 [[ 85  32   7]
  [ 15  20  30]
  [ 35  79  29]
  [ 71  23  91]]

 [[ 46  51  60]
  [  1  63   8]
  [ 31  77  58]
  [ 18  49  51]]]

Elements greater than 50:
[ 57  90  58  76  95  51  77  97  65  74  98  74 100  69  88  69  65  65
  53  76  76  85  79  71  91  51  60  63  77  58  51]

Mean along second axis:
[[30.25 76.75 70.5 ]
 [54.   74.   57.  ]
 [44.75 37.25 27.75]
 [51.5  38.5  39.25]
 [24.   60.   44.25]]

Array after replacing elements < 20 with -1:
[[[ 29  57  90]
  [ -1  58  76]
  [ -1  95  51]
  [ 77  97  65]]

 [[ 74  98  74]
  [100  45  69]
  [ -1  88  69]
  [ 39  65  -1]]

 [[ -1  24  65]
  [ 53  -1  35]
  [ 44  35  -1]
  [ 76  76  -1]]

 [[ 85  32  -1]
  [ -1  20  30]
  [ 35  79  29]
  [ 71  23  91]]

 [[ 46  51  60]
  [ -1  63  -1]
  [ 31  77  58]
  [ -1  49 

## 2. Financial Data Analysis

Given a NumPy array representing daily stock prices for a year, calculate:
- The 7-day and 30-day moving averages
- The daily returns (percentage change)
- The cumulative returns
- The annualized volatility

In [2]:
import numpy as np

# Generate sample stock prices for a year
np.random.seed(0)
stock_prices = np.random.randint(100, 200, 252)  # 252 trading days in a year

# Calculate 7-day and 30-day moving averages
ma_7 = np.convolve(stock_prices, np.ones(7), 'valid') / 7
ma_30 = np.convolve(stock_prices, np.ones(30), 'valid') / 30

# Calculate daily returns
daily_returns = np.diff(stock_prices) / stock_prices[:-1] * 100

# Calculate cumulative returns
cumulative_returns = np.cumprod(1 + daily_returns / 100) - 1

# Calculate annualized volatility
annualized_volatility = np.std(daily_returns) * np.sqrt(252)

print("First 10 stock prices:", stock_prices[:10])
print("\n7-day moving average (first 5):", ma_7[:5])
print("30-day moving average (first 5):", ma_30[:5])
print("\nDaily returns (first 5):", daily_returns[:5])
print("\nCumulative returns (first 5):", cumulative_returns[:5])
print(f"\nAnnualized volatility: {annualized_volatility:.2f}%")

First 10 stock prices: [144 147 164 167 167 109 183 121 136 187]

7-day moving average (first 5): [154.42857143 151.14285714 149.57142857 152.85714286 153.28571429]
30-day moving average (first 5): [157.16666667 157.26666667 157.83333333 158.43333333 159.5       ]

Daily returns (first 5): [  2.08333333  11.56462585   1.82926829   0.         -34.73053892]

Cumulative returns (first 5): [ 0.02083333  0.13888889  0.15972222  0.15972222 -0.24305556]

Annualized volatility: 488.13%


## 3. Image Processing with NumPy

Load a grayscale image as a 2D NumPy array. Implement the following operations:
- Apply a threshold to create a binary image
- Implement a custom edge detection algorithm using array slicing
- Rotate the image by 45 degrees using NumPy's linear algebra functions

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from skimage import io
from scipy.ndimage import rotate

# Load a sample grayscale image
image = io.imread('sample_image.png', as_gray=True)

# Apply threshold
threshold = 0.5
binary_image = (image > threshold).astype(np.float32)

# Custom edge detection
def edge_detection(img):
    vertical_edges = img[1:, :] - img[:-1, :]
    horizontal_edges = img[:, 1:] - img[:, :-1]
    return np.sqrt(vertical_edges[:, :-1]**2 + horizontal_edges[:-1, :]**2)

edges = edge_detection(image)

# Rotate image
rotated_image = rotate(image, 45, reshape=False)

# Display results
fig, axs = plt.subplots(2, 2, figsize=(12, 12))
axs[0, 0].imshow(image, cmap='gray')
axs[0, 0].set_title('Original Image')
axs[0, 1].imshow(binary_image, cmap='gray')
axs[0, 1].set_title('Binary Image')
axs[1, 0].imshow(edges, cmap='gray')
axs[1, 0].set_title('Edge Detection')
axs[1, 1].imshow(rotated_image, cmap='gray')
axs[1, 1].set_title('Rotated Image')
plt.tight_layout()
plt.show()

ModuleNotFoundError: No module named 'skimage'

## 4. Monte Carlo Simulation

Use NumPy's random module to perform a Monte Carlo simulation of stock price movements:
- Generate 1000 possible price paths for a stock over 252 trading days
- Calculate the expected price and 95% confidence interval at the end of the period
- Visualize the results using a histogram and line plot

In [4]:
import numpy as np
import matplotlib.pyplot as plt

# Set parameters
S0 = 100  # Initial stock price
mu = 0.1  # Expected annual return
sigma = 0.2  # Annual volatility
T = 1.0  # Time in years
N = 252  # Number of trading days
num_simulations = 1000

# Generate price paths
dt = T/N
nudt = (mu-0.5*sigma**2)*dt
sigdt = sigma*np.sqrt(dt)
S = S0 * np.exp(np.cumsum(nudt + sigdt*np.random.randn(num_simulations, N), axis=1))

# Calculate statistics
expected_price = np.mean(S[:, -1])
confidence_interval = np.percentile(S[:, -1], [2.5, 97.5])

# Visualize results
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.plot(S[:100, :].T, alpha=0.1)
plt.title('Sample Price Paths')
plt.xlabel('Trading Days')
plt.ylabel('Stock Price')

plt.subplot(1, 2, 2)
plt.hist(S[:, -1], bins=50, density=True)
plt.axvline(expected_price, color='r', linestyle='dashed', linewidth=2)
plt.axvline(confidence_interval[0], color='g', linestyle='dashed', linewidth=2)
plt.axvline(confidence_interval[1], color='g', linestyle='dashed', linewidth=2)
plt.title('Distribution of Final Stock Prices')
plt.xlabel('Stock Price')
plt.ylabel('Density')

plt.tight_layout()
plt.show()

print(f"Expected price: ${expected_price:.2f}")
print(f"95% Confidence Interval: (${confidence_interval[0]:.2f}, ${confidence_interval[1]:.2f})")

Expected price: $110.99
95% Confidence Interval: ($74.26, $158.10)


## 5. Custom Ufunc Creation

Implement a custom universal function that calculates the Fibonacci sequence up to n terms. Use np.frompyfunc() to vectorize your implementation.

In [5]:
import numpy as np

def fibonacci(n):
    if n < 2:
        return n
    return fibonacci(n-1) + fibonacci(n-2)

vectorized_fibonacci = np.frompyfunc(fibonacci, 1, 1)

# Test the vectorized function
n_values = np.arange(10)
fib_sequence = vectorized_fibonacci(n_values)

print("n values:", n_values)
print("Fibonacci sequence:", fib_sequence)

n values: [0 1 2 3 4 5 6 7 8 9]
Fibonacci sequence: [0 1 1 2 3 5 8 13 21 34]


## 6. Advanced Linear Algebra

Given two matrices A and B:
- Solve the system of linear equations Ax = B
- Calculate the eigenvalues and eigenvectors of A
- Perform Singular Value Decomposition (SVD) on A

In [6]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 11])

# Solve the system of linear equations
x = np.linalg.solve(A, B)
print("Solution to Ax = B:")
print(x)

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

# Perform SVD
U, S, Vt = np.linalg.svd(A)
print("\nSingular Value Decomposition:")
print("U:")
print(U)
print("\nS:")
print(S)
print("\nV^T:")
print(Vt)

Solution to Ax = B:
[1. 2.]

Eigenvalues:
[-0.37228132  5.37228132]

Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Singular Value Decomposition:
U:
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]

S:
[5.4649857  0.36596619]

V^T:
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


## 7. Performance Benchmark

Compare the performance of a pure Python implementation vs a NumPy implementation for calculating the correlation coefficient between two large datasets. Use %timeit in IPython to measure execution times.

In [ ]:
import numpy as np
from math import sqrt

def python_correlation(x, y):
    n = len(x)
    sum_x = sum(x)
    sum_y = sum(y)
    sum_xy = sum(x[i] * y[i] for i in range(n))
    sum_x2 = sum(x[i]**2 for i in range(n))
    sum_y2 = sum(y[i]**2 for i in range(n))
    
    numerator = n * sum_xy - sum_x * sum_y
    denominator = sqrt((n * sum_x2 - sum_x**2) * (n * sum_y2 - sum_y**2))
    
    return numerator / denominator

def numpy_correlation(x, y):
    return np.corrcoef(x, y)[0, 1]

# Generate large datasets
np.random.seed(0)
x = np.random.randn(100000)
y = np.random.randn(100000)

# Benchmark Python implementation
%timeit python_correlation(x, y)

# Benchmark NumPy implementation
%timeit numpy_correlation(x, y)

# Verify results
print(f"Python correlation: {python_correlation(x, y)}")
print(f"NumPy correlation: {numpy_correlation(x, y)}")

1.02 s ± 167 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
10.5 ms ± 286 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
